CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  key VARCHAR(64) NOT NULL,
  active INTEGER NOT NULL DEFAULT 1,
  description TEXT null,
  created TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
