// Generated by Wrangler by running `wrangler types`

interface Env {
	MAGIC_TRAVEL_READY: true;
	MAGIC_TRAVEL_STATUS: "Online, in early testing";
	GMAPS_API_KEY: string;
	PUBLIC_API_KEY: string;
	DEPLOYMENT_META: { id: string; tag: string };
}
