// Generated by Wrangler by running `wrangler types`

interface Env {
	ROUTES_CACHE: KVNamespace;
	MAGIC_TRAVEL_READY: true;
	MAGIC_TRAVEL_STATUS: "Online, in early testing";
	GMAPS_API_KEY: string;
	PUBLIC_API_KEY: string;
	MAGIC_TRAVEL_DB: D1Database;
	MAGIC_TRAVEL_ANALYTICS: AnalyticsEngineDataset;
	DEPLOYMENT_META: { id: string; tag: string };
}
